# Generated by Django 3.1.5 on 2021-01-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('appraisal_id', models.AutoField(primary_key=True, serialize=False)),
                ('criteria', models.CharField(blank=True, max_length=255, verbose_name='Criteria')),
                ('year', models.DateField(null=True, verbose_name='Year of Appraisal')),
                ('score', models.IntegerField(blank=True, verbose_name='Overall Performance')),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, max_length=25, verbose_name='Department')),
            ],
            options={
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='Gender')),
                ('dob', models.DateField(null=True, verbose_name='Date of birth')),
                ('nationality', models.CharField(blank=True, max_length=50, verbose_name='Nationality')),
                ('email_address', models.CharField(blank=True, max_length=50, verbose_name='Email Address')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Address')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Postal Code')),
                ('date_joined', models.DateField(null=True, verbose_name='Date Joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(blank=True, max_length=25, verbose_name='Name')),
                ('manager_title', models.CharField(blank=True, max_length=25, verbose_name='Manager Title')),
            ],
            options={
                'verbose_name_plural': 'Managers',
            },
        ),
    ]
