# Generated by Django 3.1.5 on 2021-01-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210125_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='manager_name',
        ),
    ]
