# Generated by Django 3.1.5 on 2021-01-25 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.manager'),
        ),
    ]
